export const SHOWFOR = 10;
export const SUCCESS_APPROVECLAIMS = 'Approved Selected Claim(s)!';
export const SUCCESS_UNAPPROVECLAIMS = 'Unapproved Selected Claim(s)!';
export const SUCCESS_DELETEEVENTTRANSC = 'Deleted Selected Event Transaction(s)!';
export const SUCCESS_ADDEVENTTRANSC = 'Added New Transaction!';
export const SUCCESS_DELETEEVENT = 'Deleted Selected Event(s)';
export const SUCCESS_UPDATERSVP = 'Updated Selected Registration(s)';
export const SUCCESS_NEWEVENT = 'New Event has been created!';
export const SUCCESS_NEWEVENTRSVP = 'New Event RSVP has been created!';
export const SUCCESS_UPDATEEVENT = 'Event has been updated!';
export const SUCCESS_DELETEMEMBER = 'Deleted Selected Member(s)';
export const SUCCESS_NOTIFYEVENT = 'Event Notification has been sent to the members';
export const SUCCESS_UPDATEMEMBER = 'Member has been updated!';
export const SUCCESS_RENEWMEMBER = 'Member has been renewed!';
export const SUCCESS_UPDATEASSIGNROLE = 'Member(s) Role has been updated!';
export const SUCCESS_DELETEROLE = 'Deleted Selected Role(s)';
export const SUCCESS_NEWROLE = 'New Role has been created!';
export const SUCCESS_UPDATEROLE = 'Role has been updated with newly assigned functions!';
export const SUCCESS_DELETEINCIDENT = 'Deleted Selected Incident(s)';
export const SUCCESS_NEWINCIDENT = 'New Incident has been created!';
export const SUCCESS_UPDATEINCIDENT = 'Incident has been updated!';

export const CONFIRM_DELETEEVENT = 'Please confirm to delete this event!';
export const CONFIRM_DELETEMEMBER = 'Please confirm to delete the member profile!';
export const CONFIRM_RENEWMEMBER = 'Please confirm to renew the member!';
export const CONFIRM_CREATEACC = 'Please confirm to signup!';
export const CONFIRM_DELETEINCIDENT = 'Please confirm to delete this incident!';

export const FB_EVENT_PRETEXT = 'Myanmar Club New Event! ';
